#!/bin/sh
set -e

echo "-- Generated by collect_rules.sh"
echo

echo "module Rules(rules) where"
echo

for a in Rules/*; do
    b=$(echo $a | sed -ne 's/^Rules\/\(.*\)\.l\?hs$/\1/p')

    echo "import qualified Rules.$b";

done;
echo
echo "rules = concat"



for a in Rules/*; do
    b=$(echo $a | sed -ne 's/^Rules\/\(.*\)\.l\?hs$/\1/p')
    if test -n "$seen"; then
    echo "  ,Rules.$b.rules";
    else
    echo "  [Rules.$b.rules";
    seen=1
    fi


done;

echo "   ]";
