# dependencies generated by hmake -M:
Version.o: Version.hs 
GetOpt.o: GetOpt.hs 
PreludData.o: PreludData.hs DataP.o 
StandardRules.o: StandardRules.hs RuleUtils.o GenUtil.o 
RuleMonoid.o: RuleMonoid.hs RuleUtils.o 
RuleFunctorM.o: RuleFunctorM.hs RuleUtils.o 
RuleUtility.o: RuleUtility.hs RuleUtils.o GenUtil.o 
UserRuleGhcBinary.o: UserRuleGhcBinary.hs RuleUtils.o 
UserRulesGeneric.o: UserRulesGeneric.hs RuleUtils.o 
UserRuleXml.o: UserRuleXml.hs RuleUtils.o 
UserRuleBinary.o: UserRuleBinary.hs RuleUtils.o 
UserRules.o: UserRules.hs RuleUtils.o UserRuleBinary.o UserRuleXml.o UserRulesGeneric.o UserRuleGhcBinary.o RuleUtility.o RuleFunctorM.o RuleMonoid.o 
GenUtil.o: GenUtil.hs 
Literate.o: Literate.lhs 
CommandP.o: CommandP.hs ParseLib2.o DataP.o 
ParseLib2.o: ParseLib2.hs 
DataP.o: DataP.lhs ParseLib2.o 
Pretty.o: Pretty.lhs 
RuleUtils.o: RuleUtils.hs Pretty.o DataP.o 
ChaseImports.o: ChaseImports.hs RuleUtils.o DataP.o CommandP.o ParseLib2.o Literate.o GenUtil.o 
DrIFT.o: DrIFT.hs ChaseImports.o UserRules.o StandardRules.o RuleUtils.o PreludData.o DataP.o Pretty.o GetOpt.o RuleUtils.o Version.o GenUtil.o 
