# DO NOT DELETE: Beginning of Haskell dependencies
Literate.o : Literate.lhs
GetOpt.o : GetOpt.hs
Version.o : Version.hs
GenUtil.o : GenUtil.hs
ParseLib2.o : ParseLib2.hs
DataP.o : DataP.lhs
DataP.o : ParseLib2.hi
PreludData.o : PreludData.hs
PreludData.o : DataP.hi
CommandP.o : CommandP.hs
CommandP.o : DataP.hi
CommandP.o : ParseLib2.hi
Pretty.o : Pretty.lhs
RuleUtils.o : RuleUtils.hs
RuleUtils.o : DataP.hi
RuleUtils.o : Pretty.hi
Rules/Xml.o : Rules/Xml.hs
Rules/Xml.o : RuleUtils.hi
Rules/Utility.o : Rules/Utility.hs
Rules/Utility.o : GenUtil.hi
Rules/Utility.o : RuleUtils.hi
Rules/Standard.o : Rules/Standard.hs
Rules/Standard.o : GenUtil.hi
Rules/Standard.o : RuleUtils.hi
Rules/Monoid.o : Rules/Monoid.hs
Rules/Monoid.o : RuleUtils.hi
Rules/GhcBinary.o : Rules/GhcBinary.hs
Rules/GhcBinary.o : RuleUtils.hi
Rules/Generic.o : Rules/Generic.hs
Rules/Generic.o : RuleUtils.hi
Rules/FunctorM.o : Rules/FunctorM.hs
Rules/FunctorM.o : RuleUtils.hi
Rules/BitsBinary.o : Rules/BitsBinary.hs
Rules/BitsBinary.o : RuleUtils.hi
Rules/Binary.o : Rules/Binary.hs
Rules/Binary.o : RuleUtils.hi
Rules/Arbitrary.o : Rules/Arbitrary.hs
Rules/Arbitrary.o : RuleUtils.hi
Rules.o : Rules.hs
Rules.o : Rules/Xml.hi
Rules.o : Rules/Utility.hi
Rules.o : Rules/Standard.hi
Rules.o : Rules/Monoid.hi
Rules.o : Rules/GhcBinary.hi
Rules.o : Rules/Generic.hi
Rules.o : Rules/FunctorM.hi
Rules.o : Rules/BitsBinary.hi
Rules.o : Rules/Binary.hi
Rules.o : Rules/Arbitrary.hi
ChaseImports.o : ChaseImports.hs
ChaseImports.o : GenUtil.hi
ChaseImports.o : Literate.hi
ChaseImports.o : ParseLib2.hi
ChaseImports.o : CommandP.hi
ChaseImports.o : DataP.hi
ChaseImports.o : RuleUtils.hi
DrIFT.o : DrIFT.hs
DrIFT.o : Rules.hi
DrIFT.o : Version.hi
DrIFT.o : RuleUtils.hi
DrIFT.o : RuleUtils.hi
DrIFT.o : Pretty.hi
DrIFT.o : PreludData.hi
DrIFT.o : GetOpt.hi
DrIFT.o : GenUtil.hi
DrIFT.o : DataP.hi
DrIFT.o : ChaseImports.hi
# DO NOT DELETE: End of Haskell dependencies
